// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzxtulmcqhnpaymxjnzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eHR1bG1jcWhucGF5bXhqbnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTM0NDgsImV4cCI6MjA3MzE2OTQ0OH0.H8mdGgTrPUimhkg6nNLgCe9-F-HEF3Y5S7hHwAVhfOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});